### ISSUE TITLE
Self hosted: saved paste doesn't wrap

### ISSUE THREAD

**Issue by gorangrbic** [seejohnrun/haste-server#289]
Sorry if this has already been answered but I'm having an issue with fixing a saved paste overflowing off screen and creating a horizontal scroll bar that will continue indefinitely. The only workaround is to format a new paste with line breaks 

While I've fixed the initial box width, I'm having trouble locating the pasted note box configuration. I thought it was controlled by this block in solarized_dark.css, but I'm wrong. 
```css
.hljs {
  display: block;
  padding: 0.5em;
  background: #f0ead6;
  color: #839496; /*teal gray*/
}
```
Copying a section from solarized_dark.css as HTML (gnometerm), for example, produces the following. On the bottom, you can see the vertical bar that extends out past the screen.

![logo](https://i.imgur.com/zJkDroh.png)

Any help would be appreciated, thanks! :)
